# -*- coding: utf-8 -*-
"""RETO 4 CALCULADORA

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12MNKV0yUSgp5a5ZQs-ypQlfWEzO4zaGR
"""

import math                  #AQUI IMPORTAMOS LAS LIBRERIAS A USAR
import statistics

def Menu():
    print("                       *                      :: C A L C U L A D O R A ::                       *")
    print("                       *                                                                        *")
    print("                       º  1.- Suma        2.- Resta       3.-Multiplicación      4.- División   º")
    print("                       º                                                                        º")
    print("                       º  5.- Residuo     6.- Potencia    7.- Raíz Cudrada       8.- Seno       º")
    print("                       º                                                                        º")
    print("                       º  9.- Arcoseno    10.- Coseno     11.- Log en base 10    12.- Factorial º")
    print("                       º                                                                        º")
    print("                       º  13.- Val. Abs   14.- Inverso    15.-Promedio           16.- Mediana   º")
    print("                       º                                                                        º")
    print("                       º  17.- Salir                                                            º")



def Calculadora():
 
    Menu()
 
    opc = int(input("Selecione nº de Opción: "))
 
    while (opc >1 and opc <17):
 
        if (opc==1):
            print("")
            num1 = int(input("Ingrese Primer Número: "))
            print("")
            num2 = int(input("Ingrese Segundo Número: "))
            print("")
            print ('La Suma es:', num1+num2)
            print("")

            Continuar = input("¿Desea Continuar con esta Opción?(S/N): ")
 
            if Continuar == "s" or Continuar == "S":
                opc = 1
 
            elif Continuar == "n" or Continuar == "N":
                print("")
                opc = int(input("Selecione nº de Opción: "))
 
            else:
                print("")
                Continuar = input("Por Favor escoja(S/N): ")
 
                if Continuar == "s" or Continuar == "S":
                    opc = 1
 
                elif Continuar == "n" or Continuar == "N":
                    print("")
                    opc = int(input("Selecione nº de Opción: "))
        
        elif(opc==2):
            print("")
            num1 = int(input("Ingrese Primer Número: "))
            print("")
            num2 = int(input("Ingrese Segundo Número: "))
            print("")
            print ('La Resta es:',num1-num2)
            print("")
            Continuar = input("¿Desea Continuar con esta Opción?(S/N): ")
 
            if Continuar == "s" or Continuar == "S":
                opc = 2
 
            elif Continuar == "n" or Continuar == "N":
                print("")
                opc = int(input("Selecione nº de Opción: "))
 
            else:
                print("")
                Continuar = input("Por Favor escoja(S/N): ")
 
                if Continuar == "s" or Continuar == "S":
                    opc = 2
 
                elif Continuar == "n" or Continuar == "N":
                    print("")
                    opc = int(input("Selecione nº de Opción: "))
 
        elif(opc==3):
            print("")
            num1 = int(input("Ingrese Primer Número: "))
            print("")
            num2 = int(input("Ingrese Segundo Número: "))
            print("")
            print ('La Multiplicacion es:', num1*num2)
            print("")
            Continuar = input("¿Desea Continuar con esta Opción?(S/N): ")
 
            if Continuar == "s" or Continuar == "S":
                opc = 3
 
            elif Continuar == "n" or Continuar == "N":
                print("")
                opc = int(input("Selecione nº de Opción: "))
 
            else:
                print("")
                Continuar = input("Por Favor escoja(S/N): ")
 
                if Continuar == "s" or Continuar == "S":
                    opc = 3
 
                elif Continuar == "n" or Continuar == "N":
                    print("")
                    opc = int(input("Selecione nº de Opción: "))
 
        elif(opc==4):
            print("")
            num1 = int(input("Ingrese Primer Número: "))
            print("")
            num2 = int(input("Ingrese Segundo Número: "))
            print("")
 
            try:
              print ('La Division es:', num1/num2)
              print("")
              Continuar = input("¿Desea Continuar con esta Opción?(S/N): ")
 
              if Continuar == "s" or Continuar == "S":
                opc = 4
 
              elif Continuar == "n" or Continuar == "N":
                print("")
                opc = int(input("Selecione nº de Opción: "))
 
              else:
                print("")
                Continuar = input("Por Favor escoja(S/N): ")
 
                if Continuar == "s" or Continuar == "S":
                    opc = 4
 
                elif Continuar == "n" or Continuar == "N":
                    print("")
                    opc = int(input("Selecione nº de Opción: "))
 
            except ZeroDivisionError:
              print ('No se Permite la Division Entre 0')
              print("")
              Continuar = input("¿Desea Continuar con esta Opción?(S/N): ")
 
              if Continuar == "s" or Continuar == "S":
                opc = 4
 
              elif Continuar == "n" or Continuar == "N":
                print("")
                opc = int(input("Selecione nº de Opción: "))
 
              else:
                print("")
                Continuar = input("Por Favor escoja(S/N): ")
 
                if Continuar == "s" or Continuar == "S":
                    opc = 4
 
                elif Continuar == "n" or Continuar == "N":
                    print("")
                    opc = int(input("Selecione nº de Opción: "))

        elif(opc==5):
            print("")
            num1 = int(input("Ingrese Primer Número: "))
            print("")
            num2 = int(input("Ingrese Segundo Número: "))
            print("")
            print ('El Resto es:', num1%num2)
            print("")
            Continuar = input("¿Desea Continuar con esta Opción?(S/N): ")
 
            if Continuar == "s" or Continuar == "S":
                opc = 5
 
            elif Continuar == "n" or Continuar == "N":
                print("")
                opc = int(input("Selecione nº de Opción: "))
 
            else:
                print("")
                Continuar = input("Por Favor escoja(S/N): ")
 
                if Continuar == "s" or Continuar == "S":
                    opc = 5
 
                elif Continuar == "n" or Continuar == "N":
                    print("")
                    opc = int(input("Selecione nº de Opción: "))
 
        elif(opc==6):
            print("")
            base = int(input("Ingrese Base: "))
            print("")
            exponente = int(input("Ingrese Exponente: "))
            print("")
            print('La Potencia es:', base**exponente)
            print("")
            Continuar = input("¿Desea Continuar con esta Opción?(S/N): ")
 
            if Continuar == "s" or Continuar == "S":
                opc = 6
 
            elif Continuar == "n" or Continuar == "N":
                print("")
                opc = int(input("Selecione nº de Opción: "))
 
            else:
                print("")
                Continuar = input("Por Favor escoja(S/N): ")
 
                if Continuar == "s" or Continuar == "S":
                    opc = 6
 
                elif Continuar == "n" or Continuar == "N":
                    print("")
                    opc = int(input("Selecione nº de Opción: "))
 
        elif(opc==7):
            print("")
            num = int(input("Ingrese Número: "))
            print("")
            print("La raíz cuadrada de {} es {}".format(num, math.sqrt(num)))
            print("")
            Continuar = input("¿Desea Continuar con esta Opción?(S/N): ")
 
            if Continuar == "s" or Continuar == "S":
                opc = 7
 
            elif Continuar == "n" or Continuar == "N":
                print("")
                opc = int(input("SSelecione nº de Opción: "))
 
            else:
                print("")
                Continuar = input("Por Favor escoja(S/N): ")
 
                if Continuar == "s" or Continuar == "S":
                    opc = 7
 
                elif Continuar == "n" or Continuar == "N":
                    print("")
                    opc = int(input("Selecione nº de Opción: "))
 
        elif(opc==8):
            print("")
            radianes = int(input("Ingrese Radianes: "))
            print("")
            print("El seno de {} es {}".format(radianes, math.sin(radianes)))
            print("")
            Continuar = input("¿Desea Continuar con esta Opción?(S/N): ")
 
            if Continuar == "s" or Continuar == "S":
                opc = 8
 
            elif Continuar == "n" or Continuar == "N":
                print("")
                opc = int(input("Selecione nº de Opción: "))
 
            else:
 
                print("")
                Continuar = input("Por Favor escoja(S/N): ")
 
                if Continuar == "s" or Continuar == "S":
                    opc = 8
 
                elif Continuar == "n" or Continuar == "N":
                    print("")
                    opc = int(input("Selecione nº de Opción: "))
 
        elif(opc==9):
            print("")
            radianes = int(input("Ingrese Radianes: "))
            print("")
            print("El arcoseno de {} es {}".format(radianes, math.asin(radianes)))
            print("")
            Continuar = input("¿Desea Continuar con esta Opción?(S/N): ")
 
            if Continuar == "s" or Continuar == "S":
                opc = 9
 
            elif Continuar == "n" or Continuar == "N":
                print("")
                opc = int(input("Selecione nº de Opción: "))
 
            else:
                print("")
                Continuar = input("Por Favor escoja(S/N): ")
 
                if Continuar == "s" or Continuar == "S":
                    opc = 9
 
                elif Continuar == "n" or Continuar == "N":
                    print("")
                    opc = int(input("Selecione nº de Opción: "))
 
        elif(opc==10):
            print("")
            radianes = int(input("Ingrese Radianes: "))
            print("")
            print("El coseno de {} es {}".format(radianes, math.cos(radianes)))
            print("")
            Continuar = input("¿Desea Continuar con esta Opción?(S/N): ")
 
            if Continuar == "s" or Continuar == "S":
                opc = 10
 
            elif Continuar == "n" or Continuar == "N":
                print("")
                opc = int(input("Selecione nº de Opción: "))
 
            else:
                print("")
                Continuar = input("Por Favor escoja(S/N): ")
 
                if Continuar == "s" or Continuar == "S":
                    opc = 10
 
                elif Continuar == "n" or Continuar == "N":
                    print("")
                    opc = int(input("Selecione nº de Opción: "))

        elif (opc== 11):
          print("")
          valorlog= int(input("ingrese el valor del log que quiere hayar"))
          print("")
          print("El logaritmo en base 10 de {} es {}".format(valorlog, math.log10(valorlog)))
          print("")
          Continuar = input("¿Desea Continuar con esta Opción?(S/N): ")

          if Continuar == "s" or Continuar == "S":
            opc = 11
          elif Continuar == "n" or Continuar == "N":
             print("")
             opc = int(input("Selecione nº de Opción: "))
 
          else:
            print("")
            Continuar = input("Por Favor escoja(S/N): ")
 
          if Continuar == "s" or Continuar == "S":
            opc = 10
 
          elif Continuar == "n" or Continuar == "N":
            print("")
            opc = int(input("Selecione nº de Opción: "))

        elif(opc==12):
            print("")
            numf = int(input("Ingrese Número: "))     
            print("El factorial de {} es {}".format(numf, math.factorial(numf)))
            print("")
            Continuar = input("¿Desea Continuar con esta Opción?(S/N): ")
 
            if Continuar == "s" or Continuar == "S":
                    opc = 12
 
            elif Continuar == "n" or Continuar == "N":
              print("")
              opc = int(input("SSelecione nº de Opción: "))
 
            else:              
              print("")
              Continuar = input("Por Favor escoja(S/N): ")
 
              if Continuar == "s" or Continuar == "S":
                  opc = 12
 
              elif Continuar == "n" or Continuar == "N":
                  print("")
                  opc = int(input("Selecione nº de Opción: "))       

        elif(opc==13):
            print("")
            num = int(input("Ingrese Número: "))
            print("")
            print("El valor absoluto de {} es {}".format(num, math.fabs(num)))
            print("")
            Continuar = input("¿Desea Continuar con esta Opción?(S/N): ")
 
            if Continuar == "s" or Continuar == "S":
                opc = 13
 
            elif Continuar == "n" or Continuar == "N":
                print("")
                opc = int(input("Selecione nº de Opción: "))
 
            else:
                print("")
                Continuar = input("Por Favor escoja(S/N): ")
 
                if Continuar == "s" or Continuar == "S":
                    opc = 13
 
                elif Continuar == "n" or Continuar == "N":
                    print("")
                    opc = int(input("Selecione nº de Opción: "))

        elif (opc==14):
          print("")
          num= float(input("Ingrese el numero:  "))
          inverso= 1/num
          print(f'el inverso del {num} es {inverso} ')

          Continuar = input("¿Desea Continuar con esta Opción?(S/N): ")
          if Continuar == "s" or Continuar == "S":
                opc = 14
          elif Continuar == "n" or Continuar == "N":
                print("")
                opc = int(input("SSelecione nº de Opción: "))
          else:
                print("")
                Continuar = input("Por Favor escoja(S/N): ") 
          if Continuar == "s" or Continuar == "S":
                    opc = 14 
          elif Continuar == "n" or Continuar == "N":
                    print("")
                    opc = int(input("Selecione nº de Opción: "))

        elif (opc==15):

          listprom = []
          
          cantidadprom= int(input("Cuantos datos desea agregar: "))
          while cantidadprom>0:
            datoprom = input("Ingrese sus datos: ")
            listprom.append(float(datoprom))
            cantidad-=1
          print(statistics.mean(listprom))

          Continuar = input("¿Desea Continuar con esta Opción?(S/N): ")

          if Continuar == "s" or Continuar == "S":
                opc = 15
 
          elif Continuar == "n" or Continuar == "N":
            print("")
            opc = int(input("Selecione nº de Opción: "))
 
          else:
            print("")
            Continuar = input("Por Favor escoja(S/N): ")
        
        elif (opc==16):
          listame = []
          cantidad = int(input("Cuantos datos desea agregar: "))
          while cantidad>0:
              datome = input("Ingrese sus datos: ")
              listame.append(float(datome))
              cantidad-=1
          print(statistics.median(listame))
          print("")
          Continuar = input("¿Desea Continuar con esta Opción?(S/N): ")

          if Continuar == "s" or Continuar == "S":
                opc = 16
 
          elif Continuar == "n" or Continuar == "N":
            print("")
            opc = int(input("Selecione nº de Opción: "))
 
          else:
            print("")
            Continuar = input("Por Favor escoja(S/N): ")
        
        elif(opc==17):
            break
 
    while(opc <1 or opc >17 ):
        print("")
        print("Opción no Encontrada")
        print("")
        opc = int(input("Selecione nº de Opción: "))
 
Calculadora()